### ISSUE TITLE
grafana里显示git统计数据

### ISSUE THREAD

**Issue by oylbin** [NDHWAlliance/gitlab-analytics#1]
表结构

    CREATE TABLE `gitlab_commits` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `project_id` int(11) NOT NULL,
      `project_path` varchar(128) CHARACTER SET latin1 NOT NULL,
      `commit_id` char(40) CHARACTER SET latin1 NOT NULL,
      `title` varchar(72) NOT NULL,
      `created_at` datetime NOT NULL,
      `parent_ids` int(11) NOT NULL,
      `message` varchar(255) NOT NULL,
      `author_name` varchar(64) NOT NULL,
      `author_email` varchar(64) CHARACTER SET latin1 NOT NULL,
      `authored_date` datetime NOT NULL,
      `committer_name` varchar(64) NOT NULL,
      `committer_email` varchar(64) NOT NULL,
      `committed_date` datetime NOT NULL,
      `line_additions` int(11) DEFAULT NULL,
      `line_deletions` int(11) DEFAULT NULL,
      `line_total` int(11) DEFAULT NULL,
      `ignore` int(11) DEFAULT '0' COMMENT 'ignore this commit when analyze contribution',
      PRIMARY KEY (`id`),
      UNIQUE KEY `commit_id` (`commit_id`,`project_id`) USING BTREE,
      KEY `author_email` (`author_email`),
      KEY `author_name` (`author_name`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
    
在grafana里添加mysql data source，然后配置表

![image](https://user-images.githubusercontent.com/408037/41698465-1e4e5704-7551-11e8-8c6d-3d766a2f7804.png)

```
select  author_name, author_email, count(*) as "提交次数",
    sum(line_additions) as "增加行数",
    sum(line_deletions) as "删除行数",
    sum(line_total) as "总修改行数"
from gitlab_commits
where `ignore` = 0 and $__timeFilter(authored_date)
group by author_name, author_email
```

![image](https://user-images.githubusercontent.com/408037/41698476-2934f196-7551-11e8-9770-498a46f5a41b.png)

```
select  
	$__timeGroup(authored_date,'1h') as time,
	count(*) as value
from gitlab_commits
where $__timeFilter(authored_date)
group by 1
```

**Comment by yourfccoder** [comment]
### 日志入库

1. 通过server/gitlab_analytics_models中的main函数创建表
1. 通过click调用server/log_import.py，参数传入我给你的日志文件即可入库

```shell
python3.7 log_import.py event_info -i ~/logtest/event_info.log
```

### 临时sql语句
```sql
SELECT author_name, count(*) as "issue次数"
from gitlab_issue
group by author_name;

SELECT author_name, count(*) as "wiki修改次数", sum(content_length) as "字数"
from gitlab_wiki_update
where gitlab_wiki_update.content_length < 5000
group by author_name;

SELECT author_name, count(*) as "次数"
from gitlab_merge_request
where author_name <> assignee
group by author_name

SELECT assignee, count(*) as "次数"
from gitlab_merge_request
where author_name <> assignee
group by assignee

SELECT author_name, sum(content_length) as "评论字数"
from gitlab_mr_initiator_comment
group by author_name

SELECT author_name, sum(content_length) as "评论字数"
from gitlab_mr_assignee_comment
group by author_name

SELECT author_name, sum(content_length) as "评论字数"
from gitlab_issue_comment
group by author_name
```

**Comment by oylbin** [comment]
https://github.com/NDHWAlliance/gitlab-analytics/commit/456efac376ebfe6cf1546dd448ab1f12a938d3a2

我这个commit里提到了如何更新 grafana初始化时的dashboard配置文件。

我刚刚按上面的sql添加了几个table。剩下的table你来加吧。比较简单，大部分都只需要在你的sql语句的where条件里加上 $__timeFilter(created_at) 就可以了。

@yourfccoder
