### ISSUE TITLE
如何更好地让用户初始化配置

### ISSUE THREAD

**Issue by yourfccoder** [NDHWAlliance/gitlab-analytics#10]
是否可以定义为以下流程

1. 配置完后，点击submit
1. admin接口判断private_token和url是否可以获取到projects，是的话进入后续的项目hook添加初始化，否则打印报错页面
1. 打印用户所有项目简述（id + url)，提供用户输入框输入"all"或者"1,2,4,8"id以空格分开这个样子，点击submit后自动帮用户添加上所有的hook

**Comment by oylbin** [comment]
+1
