### ISSUE TITLE
grafana up的时候失败

### ISSUE THREAD

**Issue by yourfccoder** [NDHWAlliance/gitlab-analytics#11]
OS： Centos
执行 docker-compose up grafana报如下错误

```shell
grafana    | GF_PATHS_DATA='/var/lib/grafana' is not writable.
mysql      | 180718  2:34:36 [Note] /usr/sbin/mysqld (mysqld 5.5.60-MariaDB-1~wheezy) starting as process 59 ...
grafana    | You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later
grafana    | mkdir: cannot create directory '/var/lib/grafana/plugins': Permission denied
grafana exited with code 1
```

查看 data/grafana发现用户变成了root，sudo删除data后创建data/grafana还是root用户

推测原因和临时解决方式
1. 本地volumes目录权限被设置成了root，应该是启动容器时使用root用户做了初始操作，导致目录权限变成了root
1. 以普通用户执行grafana启动会有权限问题
1. 修改docker-compose.yml的grafana服务，设置user为root，使容器CMD命令以root用户执行
1. 如果本地使用root用户启动compose应该不会出现这个问题

**Comment by oylbin** [comment]
什么意思， 必须使用root用户执行以下命令来启动？

    docker-compose up mysql grafana ga

**Comment by yourfccoder** [comment]
我这边还在查，我本地是好的，找了centos服务器启动后data/grafana变成了root，我在看是不是环境的问题
