### ISSUE TITLE
安装配置过程中重复构建镜像问题

### ISSUE THREAD

**Issue by youyang** [NDHWAlliance/gitlab-analytics#13]
![image](https://user-images.githubusercontent.com/3798485/43031604-5fc2faee-8cd7-11e8-9de1-d5d43ec78351.png)
![image](https://user-images.githubusercontent.com/3798485/43031615-7c173138-8cd7-11e8-8d2b-655320dc18c6.png)

代码建议不要做到镜像里，改了代码总要重新构建镜像，有些麻烦。如果代码稳定了也可以直接做一个镜像，这样也可以减少每个用户重复构建镜像的过程。另外pip下载文件比较慢，可以考虑配置国内的源

**Comment by oylbin** [comment]
> 代码建议不要做到镜像里，改了代码总要重新构建镜像，有些麻烦。

如果是在开发阶段，每次改代码都启动容器来测试，确实会麻烦，所以原则是开发阶段不要用容器启动server来进行测试。

正确的做法：

1. 用容器启动 mysql & grafana，

       docker-compose up mysql grafana

    注意在 docker-compose.yaml 里有配置mysql，将mysql的端口暴露出来。这样在容器外就可以访问 localhost:3306 连接上mysql。

2. 用如下方式来启动ga server，（目前代码根目录下的Makefile里有）

        MYSQL_HOST=localhost \                                                      
        MYSQL_PORT=3306  \                                                          
        MYSQL_USER=ga \                                                             
        MYSQL_PASSWORD=4t9wegcvbYSd \                                               
        MYSQL_DATABASE=gitlab_analytics \                                           
        python3 server/web.py

**Comment by oylbin** [comment]
再补充几点：

* 代码里不要hardcode任何的mysql连接参数。（gitlab_analytics_models.py里由peewee自动生成的就不管了），使用mysql连接参数时，全部都从环境变量里读。这样可以保证开发环境和实际部署环境的业务代码保持一致。
* 开发阶段，启动ga server也需要注意要正确的传递环境变量。
* 实际部署时，环境变量是在 docker-compose 里配置的。

**Comment by yourfccoder** [comment]
这个我的锅，调试的时候写死了，我修复一下 @oylbin
