### ISSUE TITLE
ga容器启动问题

### ISSUE THREAD

**Issue by liubaoxing** [NDHWAlliance/gitlab-analytics#14]
# mysql连接配置

web.py、gitlab_analytics_models.py里数据库连接地址是写死的127.0.0.1，容器里肯定连不上mysql

# ga容器启动失败

使用docker-compose up启动应用时，ga很大概率失败，感觉应该是mysql初始到监听端口的过程比较慢，ga尝试连接mysql失败后就失败退出了，导致应用启动不了（compose里配置的depends好像并不会等待mysql应用启动完成）

**Comment by oylbin** [comment]
mysql连接的问题，

gitlab_analytics_models.py 里的 MySQLDatabase 是自动化生成的，不能直接使用。

正确的做法是，在使用db之前，必须调用 web.py 里的 setup_db_connection 函数，初始化mysql的连接参数。

不过目前 setup_db_connection 的实现也有问题，mysql_host 写死了 127.0.0.1，这里应该优先读取 env里的环境变量。

@yourfccoder

**Comment by oylbin** [comment]
@liubaoxing 提到的

> 使用docker-compose up启动应用时，ga很大概率失败，感觉应该是mysql初始到监听端口的过程比较慢，ga尝试连接mysql失败后就失败退出了，导致应用启动不了（compose里配置的depends好像并不会等待mysql应用启动完成）

这个问题还是存在，需要修改代码，做好容错。
出现 DB连不上，或者 database 不存在等问题时，要等待一段时间再重试。

或者，修改README.md 里的安装部署脚本，教大家先启动mysql，再启动ga
