### ISSUE TITLE
制作ga镜像指定豆瓣源

### ISSUE THREAD

**Issue by youyang** [NDHWAlliance/gitlab-analytics#17]
RUN pip install -r requirements.txt
改成
RUN pip install -i http://pypi.douban.com/simple/ --trusted-host pypi.douban.com -r requirements.txt

**Comment by yourfccoder** [comment]
@oylbin 部署的你来定吧

**Comment by oylbin** [comment]
现在有点尴尬，我们已经写好了英文readme，可是我们代码里，`mysql/conf/custom.cnf`固定了时区`default_time_zone='+08:00'`，然后这个pip再加上豆瓣源，感觉怪怪的😓

**Comment by oylbin** [comment]
嗯，看了一下，dockerfile的build-time variables应该可以解决这个问题

参考 https://docs.docker.com/engine/reference/builder/#arg
