### ISSUE TITLE
统计哪些数据？

### ISSUE THREAD

**Issue by oylbin** [NDHWAlliance/gitlab-analytics#2]
对每个用户，统计他在一段时间段内：

* git提交次数
* 代码增加行数
* 代码删除行数
* 代码总行数
* wiki提交次数
* wiki增加行数
* wiki删除行数
* wiki总行数
* issue数量
* comments数量
* merge request数量

**Comment by oylbin** [comment]
* 参与项目数量（对项目贡献代码、编辑WIKI、提issue，comment等任何行为都认为是参与项目）

**Comment by yourfccoder** [comment]
* merge request分assignee和writer统计吧
* 我们是否应该鼓励snippet在公司内部就有一个open share的流程
