### ISSUE TITLE
gitlab 地址怎么填什么呢？

### ISSUE THREAD

**Issue by IamQiuTian** [NDHWAlliance/gitlab-analytics#22]
如题。

**Comment by IamQiuTian** [comment]
Traceback (most recent call last):
ga         |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
ga         |     return self.wsgi_app(environ, start_response)
ga         |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
ga         |     response = self.handle_exception(e)
ga         |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
ga         |     reraise(exc_type, exc_value, tb)
ga         |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
ga         |     raise value
ga         |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
ga         |     response = self.full_dispatch_request()
ga         |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
ga         |     rv = self.handle_user_exception(e)
ga         |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
ga         |     reraise(exc_type, exc_value, tb)
ga         |   File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
ga         |     raise value
ga         |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
ga         |     rv = self.dispatch_request()
ga         |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
ga         |     return self.view_functions[rule.endpoint](**req.view_args)
ga         |   File "/app/web.py", line 84, in add_hook
ga         |     for project in gitlab_api.list_all_projects():
ga         |   File "/app/gitlab_api.py", line 27, in list_all_projects
ga         |     return get_gl().projects.list(order_by='last_activity_at', as_list=False)
ga         |   File "/usr/local/lib/python3.6/site-packages/gitlab/exceptions.py", line 242, in wrapped_f
ga         |     return f(*args, **kwargs)
ga         |   File "/usr/local/lib/python3.6/site-packages/gitlab/mixins.py", line 133, in list
ga         |     obj = self.gitlab.http_list(path, **data)
ga         |   File "/usr/local/lib/python3.6/site-packages/gitlab/__init__.py", line 565, in http_list
ga         |     return GitlabList(self, url, query_data, **kwargs)
ga         |   File "/usr/local/lib/python3.6/site-packages/gitlab/__init__.py", line 671, in __init__
ga         |     self._query(url, query_data, **kwargs)
ga         |   File "/usr/local/lib/python3.6/site-packages/gitlab/__init__.py", line 692, in _query
ga         |     error_message="Failed to parse the server message")
ga         | gitlab.exceptions.GitlabParsingError: Failed to parse the server message

**Comment by yourfccoder** [comment]
就是你们的gitlab的网页入口呀，你先确认你的url和private_token能通过api/v4访问你的git仓库吗
https://docs.gitlab.com/ee/api/
