### ISSUE TITLE
统计数据是否要实时入库

### ISSUE THREAD

**Issue by yourfccoder** [NDHWAlliance/gitlab-analytics#3]
# 当前已实现
1. 自动添加hook
1. github activty通过hook收集到统一的日志

# TODO
1. 在记录日志的同时记录到mysql还是另外写一个定时任务记录到mysql
1. 区别：直接写mysql的话实现简单但是hook响应受mysql影响；定时任务异步入库耦合度低且不会影响当前gitlab的使用，而且后续如果要用hadoop或者其他的分析方式也比较好迁移

我个人倾向前期先简单同步入库，但是我们需要部署一个gitlab方便测试 @oylbin 你怎么看

**Comment by oylbin** [comment]
如果只是用gitlab测试webhook的话，直接用这个怎样？

https://gitlab.com/oylbin/test

你注册一个gitlab账号

**Comment by oylbin** [comment]
前期就同步入库吧。有性能问题再优化。
我是觉得，这个数据量应该不会大到需要hadoop来分析。

**Comment by yourfccoder** [comment]
哦，当前我们公司的量级肯定不需要，我指的是如果开源给一些大公司，当然我想多了大公司他们肯定有搞自己的一套哈哈哈，当我没说

**Comment by yourfccoder** [comment]
已注册：https://gitlab.com/oylbin/test
前期测试的话，我们先使用现成的hook数据吧，测试完后我们再创建项目逐个进行测试
