### ISSUE TITLE
自动建表是否用peewee

### ISSUE THREAD

**Issue by yourfccoder** [NDHWAlliance/gitlab-analytics#4]
用sql和peewee语句哪个好呢，反正peewee的model都要声明所有的字段那不如直接用peewee的create?
是有什么问题我没考虑到吗

**Comment by oylbin** [comment]
嗯，可以用程序建表。
后面表结构调整的话，这样用程序操作确实更合适。

**Comment by oylbin** [comment]
mysql容器启动时，只创建db和用户。

ga容器首次启动之后，用户访问时，进入setup界面。

用户在这里填写配置信息。提交时：

1. 修改mysql db的字符集。
2. 为db创建只读用户。
3. 创建数据表。
4. 保存配置信息。
