### ISSUE TITLE
是否需要打印日志

### ISSUE THREAD

**Issue by yourfccoder** [NDHWAlliance/gitlab-analytics#8]
alpha版本需要打印或记录日志方便用户查看报错吗，是不是把所有的hook_data打印到flask控制台就可以，flask控制台需要重定向一下日志吗

**Comment by oylbin** [comment]
flash里用 app.logger.info('xxx') 这样输出日志就可以了。会输出到终端。

用户用下面的方式启动ga，用`-d`参数放到后台运行

    docker-compose up -d ga

如果用户想看日志，可以这样

    docker logs ga

或者

    docker attach ga
