### ISSUE TITLE
docker-compose up mysql 报错

### ISSUE THREAD

**Issue by yourfccoder** [NDHWAlliance/gitlab-analytics#9]
版本
===
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

报错日志
===
docker-compose up mysql
Creating network "gitlab-analytics_default" with the default driver
Pulling mysql (mariadb:5.5.60)...
5.5.60: Pulling from library/mariadb
5d29656a3561: Pull complete
c093df01428e: Pull complete
f8f312305744: Pull complete
65eab2c23a31: Pull complete
2d6b76522029: Pull complete
286fd80a628b: Pull complete
1e68d6c03472: Pull complete
e40333ffae6c: Pull complete
178b0c6577b4: Pull complete
dfab54665398: Pull complete
2e23e2de2477: Pull complete
Digest: sha256:a804c0cb68745224cdc13187ddb8ca436c1320d11edfa12074653e6cc6cfdf07
Status: Downloaded newer image for mariadb:5.5.60
Creating mysql ... done
Attaching to mysql
mysql      | Initializing database
mysql      | 180709 14:52:43 [Note] /usr/sbin/mysqld (mysqld 5.5.60-MariaDB-1~wheezy) starting as process 59 ...
mysql      | 180709 14:52:43 [ERROR] Fatal error: Illegal or unknown default time zone 'Asia/Chongqing'
mysql      |

**Comment by yourfccoder** [comment]
已解决

```shell
apt-get install ntpdate
```

**Comment by oylbin** [comment]
这。。。跟NTP有关系？
